/**
 * Tüm Excel araçları için ek blog yazıları (SEO + trafik).
 * content: p, h3, ul, formula — aynı yapı.
 */
import type { BlogPost } from "./blog-posts";

const DATE = "2025-03-15";

export const BLOG_POSTS_EXTRA: BlogPost[] = [
  {
    slug: "excel-listeleri-birlestirme",
    title: "Excel'de Listeleri Birleştirme: Tek Tıkla Hepsi Tek Sütunda (Ücretsiz Araç)",
    description: "Excel listelerini tek sütunda birleştirme: BİRLEŞTİR, METNEBİRLEŞTİR veya en hızlı çözüm—ücretsiz araç.",
    date: DATE,
    toolHref: "/excel-araclari/liste-birlestir",
    toolName: "Liste Birleştirici",
    content: [
      { type: "p", text: "Farklı sütunlardaki veya sayfalardaki listeleri tek listede toplamak sık gereken bir işlem. Excel'de formülle veya hazır araçla yapabilirsiniz." },
      { type: "h3", text: "1. Yöntem: Formül ile birleştirme" },
      { type: "p", text: "Metinleri tek hücrede birleştirmek için BİRLEŞTİR veya & operatörü kullanılır. Birden fazla satırı alt alta birleştirmek için METNEBİRLEŞTİR ile satır sonu (CHAR(10)) ayırıcı verilebilir." },
      { type: "h3", text: "2. Yöntem: Araç ile birleştirme" },
      { type: "p", text: "Listeleri yapıştırıp tek listede (virgülle, satır sonuyla veya Excel'e yapıştırmaya uygun formatta) birleştiren araçlar tek tıkla sonuç verir. Çıktıyı kopyalayıp Excel'e yapıştırabilirsiniz." },
      { type: "p", text: "Özet: Küçük birleştirme için formül; birden fazla listeyi hızlıca tek yapmak için araç pratik." },
    ],
  },
  {
    slug: "excel-yinelenenleri-kaldirma",
    title: "Excel'de Yinelenenleri Kaldırma: Tekrarları Saniyede Temizle (2 Yöntem + Ücretsiz Araç)",
    description: "Excel'de tekrarlayan satırları kaldırma: Yinelenenleri Kaldır, BENZERSİZ veya tek tıkla ücretsiz araç.",
    date: DATE,
    toolHref: "/excel-araclari/tekrarlananlari-kaldir",
    toolName: "Tekrarlananları Kaldır",
    content: [
      { type: "p", text: "Aynı satırın birden fazla kez geçtiği listelerde tekrarları temizlemek raporlarda sık gerekiyor. Excel'in yerleşik özelliği veya formülle yapılabilir." },
      { type: "h3", text: "1. Yöntem: Yinelenenleri Kaldır (Veri sekmesi)" },
      { type: "ul", items: ["Veriyi seçin.", "Veri sekmesi → Yinelenenleri Kaldır.", "Hangi sütunlara göre tekrar sayılacağını seçin (tüm sütunlar aynıysa tek satır kalır).", "Tamam deyin; tekrarlar silinir."] },
      { type: "h3", text: "2. Yöntem: BENZERSİZ formülü (Excel 365)" },
      { type: "p", text: "=BENZERSİZ(aralık) ile tekrarsız liste dinamik olarak üretilir. Orijinal veri değişirse sonuç da güncellenir." },
      { type: "p", text: "Özet: Kalıcı silmek istiyorsanız Yinelenenleri Kaldır; dinamik liste istiyorsanız BENZERSİZ. Liste dışarıdaysa araçla da temizleyip sonucu Excel'e yapıştırabilirsiniz." },
    ],
  },
  {
    slug: "excelde-sayiyi-yaziya-cevirme",
    title: "Excel'de Sayıyı Yazıya Çevirme: En Kolay Yöntem + Ücretsiz Araç (TL, Kuruş)",
    description: "Fatura ve çek için sayıyı Türkçe yazıya çevirme: formül veya tek tıkla ücretsiz araç. Hızlı çözüm.",
    date: DATE,
    toolHref: "/excel-araclari/sayi-yaziya",
    toolName: "Sayıyı Yazıya Çevir",
    content: [
      { type: "p", text: "Fatura, çek veya resmi evraklarda tutarı yazıyla yazmak gerekir. Excel'de bunu formülle veya hazır araçla yapabilirsiniz." },
      { type: "h3", text: "1. Yöntem: Özel formül / VBA" },
      { type: "p", text: "Excel'de yerleşik Türkçe sayı-yazı fonksiyonu yok; genelde özel bir UDF (VBA) veya uzun formül kullanılır. Binler, milyonlar ve kuruş ayrımı dikkate alınır." },
      { type: "h3", text: "2. Yöntem: Online araç" },
      { type: "p", text: "Sayıyı yapıştırıp Türkçe yazıya (TL ve kuruş) çeviren araçlar tek tıkla sonuç verir. Çıktıyı kopyalayıp Excel'e yapıştırabilirsiniz." },
      { type: "p", text: "Özet: Tek seferlik veya az sayıda sayı için araç; her hücrede otomatik istiyorsanız formül/VBA gerekir." },
    ],
  },
  {
    slug: "excel-transpoz-satir-sutun-dondurme",
    title: "Excel'de Transpoz: Satır–Sütun Döndürme Tek Tıkla (Ücretsiz Araç)",
    description: "Excel'de satırları sütuna, sütunları satıra döndürme: Özel Yapıştır Devrik veya en hızlı çözüm—ücretsiz araç.",
    date: DATE,
    toolHref: "/excel-araclari/transpoz",
    toolName: "Satır / Sütun Döndür (Transpoz)",
    content: [
      { type: "p", text: "Yatay duran veriyi dikey veya dikeyi yatay yapmak için transpoz kullanılır. Excel'de tek komutla veya araçla yapılabilir." },
      { type: "h3", text: "1. Yöntem: Özel Yapıştır → Devrik" },
      { type: "ul", items: ["Döndüreceğiniz aralığı kopyalayın (Ctrl+C).", "Hedef hücreyi seçin (boş bir alan).", "Ctrl+Alt+V → Özel Yapıştır açılır.", "Devrik kutusunu işaretleyin, Tamam deyin."] },
      { type: "h3", text: "2. Yöntem: Araç ile transpoz" },
      { type: "p", text: "Veriyi yapıştırıp transpoz eden araçlar sonucu sekme ile verir; Excel'e yapıştırdığınızda satırlar sütun, sütunlar satır olur." },
      { type: "p", text: "Özet: Excel içinde Özel Yapıştır Devrik; veri metin olarak geliyorsa araçla transpoz edip yapıştırmak pratik." },
    ],
  },
  {
    slug: "excelde-bosluk-temizleme",
    title: "Excel'de Boşluk Temizleme: Baş-Son Boşlukları Tek Tıkla Sil (Ücretsiz Araç)",
    description: "Excel'de TEMİZLE (TRIM) veya toplu boşluk temizleme. En hızlı çözüm: ücretsiz araç.",
    date: DATE,
    toolHref: "/excel-araclari/bosluk-temizle",
    toolName: "Boşluk Temizle",
    content: [
      { type: "p", text: "Dış sistemlerden veya kopyala-yapıştırla gelen metinlerde başta, sonda veya kelime arasında gereksiz boşluklar olabilir. Bunlar eşleştirme ve sıralamada sorun çıkarır." },
      { type: "h3", text: "1. Yöntem: TEMİZLE (TRIM) formülü" },
      { type: "p", text: "=TEMİZLE(A1) baştaki ve sondaki boşlukları siler; kelimeler arasındaki birden fazla boşluğu tek boşluğa indirir. Yeni sütunda formülü aşağı çoğaltıp sonucu Değer olarak yapıştırabilirsiniz." },
      { type: "h3", text: "2. Yöntem: Araç ile toplu temizlik" },
      { type: "p", text: "Metni yapıştırıp temizleyen araçlar tek tıkla sonuç verir; çıktıyı Excel'e yapıştırabilirsiniz." },
      { type: "p", text: "Özet: Excel'de TEMİZLE; liste dışarıdaysa veya toplu temizlik istiyorsanız araç." },
    ],
  },
  {
    slug: "excelde-metni-kolonlara-bolme",
    title: "Excel'de Metni Kolonlara Bölme: Virgül/Noktalı Virgül—Hızlı Çözüm + Ücretsiz Araç",
    description: "Virgül veya noktalı virgülle ayrılmış metni sütunlara bölme: Metni Sütunlara Dönüştür veya tek tıkla ücretsiz araç.",
    date: DATE,
    toolHref: "/excel-araclari/kolonlara-bol",
    toolName: "Metni Kolonlara Böl",
    content: [
      { type: "p", text: "Tek hücrede virgül veya noktalı virgülle ayrılmış metin varsa bunu sütunlara bölmek için Excel'in Metni Sütunlara Dönüştür özelliği veya ayırıcı seçen araçlar kullanılır." },
      { type: "h3", text: "1. Yöntem: Metni Sütunlara Dönüştür" },
      { type: "ul", items: ["Veriyi seçin.", "Veri → Metni Sütunlara Dönüştür.", "Sınırlandırılmış seçin.", "Ayırıcı: virgül, noktalı virgül veya sekme seçin.", "Son deyin."] },
      { type: "h3", text: "2. Yöntem: Online araç" },
      { type: "p", text: "Metni yapıştırıp ayırıcıyı (otomatik, virgül, noktalı virgül, sekme) seçerek sütunlara bölen araçlar sonucu Excel'e yapıştırmaya uygun formatta verir." },
      { type: "p", text: "Özet: Excel'deki veri için Metni Sütunlara Dönüştür; metin dışarıdaysa araç. İkisi de aynı mantık." },
    ],
  },
  {
    slug: "excelde-buyuk-kucuk-harf-donusturme",
    title: "Excel'de Büyük Küçük Harf Dönüştürme: 3 Yöntem + Tek Tık Çözüm (Ücretsiz Araç)",
    description: "Excel'de BÜYÜKHARF, KÜÇÜKHARF, YAZIM.DÜZENİ veya tek tıkla toplu dönüştürme. Ücretsiz araç.",
    date: DATE,
    toolHref: "/excel-araclari/buyuk-kucuk-harf",
    toolName: "Büyük / Küçük Harf Dönüştür",
    content: [
      { type: "p", text: "Tüm harfleri büyütmek, küçültmek veya sadece baş harfleri büyük yapmak Excel'de formülle veya araçla yapılabilir." },
      { type: "h3", text: "Formüller" },
      { type: "ul", items: ["BÜYÜKHARF(metin) — tümü büyük.", "KÜÇÜKHARF(metin) — tümü küçük.", "YAZIM.DÜZENİ(metin) — her kelimenin ilk harfi büyük."] },
      { type: "h3", text: "Araç ile toplu dönüştürme" },
      { type: "p", text: "Metni yapıştırıp büyük/küçük/baş harf büyük seçenekleriyle dönüştüren araçlar çıktıyı kopyalayıp Excel'e yapıştırmanızı sağlar." },
      { type: "p", text: "Özet: Hücrede formül kullanın; liste dışarıdaysa veya tek seferlik toplu işlem için araç pratik." },
    ],
  },
  {
    slug: "excelde-hafta-numarasi-ve-gun-adi",
    title: "Excel'de Hafta Numarası ve Gün Adı: Tarihten Anında Çıkar (Ücretsiz Araç)",
    description: "Excel'de HAFTANINGÜNÜ, HAFTAYAÇ ile hafta numarası ve gün adı. Toplu liste için tek tıkla ücretsiz araç.",
    date: DATE,
    toolHref: "/excel-araclari/hafta-gun",
    toolName: "Hafta Numarası & Gün Adı",
    content: [
      { type: "p", text: "Tarih hücresinden haftanın kaçıncı günü (Pazartesi=1 vb.) veya hafta numarası almak raporlarda sık gerekiyor." },
      { type: "h3", text: "Formüller" },
      { type: "ul", items: ["HAFTANINGÜNÜ(tarih) — 1 (Pazar) ile 7 arası sayı.", "HAFTANINGÜNÜ(tarih;2) — 1 (Pazartesi) ile 7 (Pazar).", "HAFTAYAÇ(tarih) — yılın kaçıncı haftası.", "Gün adı için EĞER veya metin listesi ile sayıyı Pzt, Sal vb. yapabilirsiniz."] },
      { type: "h3", text: "Araç ile toplu işlem" },
      { type: "p", text: "Tarih listesini yapıştırıp hafta numarası ve gün adı sütunlarını üreten araçlar sonucu Excel'e yapıştırmaya uygun verir." },
      { type: "p", text: "Özet: Excel'de HAFTANINGÜNÜ ve HAFTAYAÇ; toplu liste için araç." },
    ],
  },
  {
    slug: "excelde-iban-dogrulama",
    title: "Excel'de IBAN Doğrulama: Listeyi Tek Tıkla Kontrol Et (Ücretsiz Araç)",
    description: "Excel'de IBAN kontrolü: uzunluk, mod 97. Geçerli/geçersiz işaretleme—en hızlı çözüm ücretsiz araç.",
    date: DATE,
    toolHref: "/excel-araclari/iban-dogrulama",
    toolName: "IBAN Doğrulama",
    content: [
      { type: "p", text: "IBAN'ların geçerli olup olmadığını kontrol etmek için uzunluk, ülke kodu ve mod 97 hesabı kullanılır. Excel'de formülle veya araçla yapılabilir." },
      { type: "h3", text: "1. Yöntem: Formül (basit kontrol)" },
      { type: "p", text: "TR IBAN 26 karakterdir; başında TR gelir. UZUNLUK ve SOL ile ilk kontrol yapılabilir; tam doğruluk için mod 97 algoritması uygulanır (formül biraz uzundur)." },
      { type: "h3", text: "2. Yöntem: Araç ile doğrulama" },
      { type: "p", text: "IBAN listesini yapıştırıp geçerli/geçersiz işaretleyen araçlar sonucu Excel'e yapıştırmaya uygun formatta verir." },
      { type: "p", text: "Özet: Az sayıda IBAN için formül; uzun liste için araç daha pratik." },
    ],
  },
  {
    slug: "excelde-faiz-hesaplama",
    title: "Excel'de Faiz Hesaplama: Basit ve Bileşik—Anında Sonuç (Ücretsiz Araç)",
    description: "Excel'de FAİZ, FAİZORAN veya tek tıkla basit/bileşik faiz. En hızlı çözüm: ücretsiz araç.",
    date: DATE,
    toolHref: "/excel-araclari/faiz-hesaplama",
    toolName: "Faiz Hesaplama",
    content: [
      { type: "p", text: "Basit faiz veya bileşik faiz hesaplamak için Excel'de FAİZ, FAİZORAN veya manuel formüller kullanılır. Kısa vadeli veya yatırım senaryolarında sık gerekiyor." },
      { type: "h3", text: "Formüller" },
      { type: "ul", items: ["Basit faiz: anapara × oran × gün/365.", "FAİZ(oran;dönem;dönem_sayısı;bd;tür) — belirli dönem faizi.", "Bileşik faiz: anapara × (1+oran)^dönem - anapara."] },
      { type: "h3", text: "Araç ile hesaplama" },
      { type: "p", text: "Anapara, oran ve vade girerek basit veya bileşik faizi hesaplayan araçlar sonucu anında gösterir; Excel'e uyumlu formatta kopyalayabilirsiniz." },
      { type: "p", text: "Özet: Karmaşık senaryolar için formül; hızlı tek hesaplar için araç." },
    ],
  },
  {
    slug: "excelde-kredi-taksit-hesaplama",
    title: "Excel'de Kredi Taksit Hesaplama: Aylık Taksit Anında (PMT + Ücretsiz Araç)",
    description: "Kredi tutarı, vade ve faizden aylık taksit: Excel PMT veya tek tıkla ücretsiz araç. Hızlı çözüm.",
    date: DATE,
    toolHref: "/excel-araclari/kredi-taksit",
    toolName: "Kredi Taksit Hesaplama",
    content: [
      { type: "p", text: "Kredi tutarı, faiz oranı ve vadeye göre aylık taksit tutarını hesaplamak için Excel'de PMT (Taksit) fonksiyonu kullanılır." },
      { type: "h3", text: "Formül" },
      { type: "p", text: "=PMT(aylık_oran; vade_ay; -ana_para) ile aylık taksit bulunur. Faiz oranı yıllıksa 12'ye bölünür. Sonuç negatif çıkabilir; mutlak değer alınabilir." },
      { type: "h3", text: "Araç ile hesaplama" },
      { type: "p", text: "Kredi tutarı, vade ve faiz oranı girerek taksit tutarını ve özet tabloyu üreten araçlar sonucu Excel'e aktarmanıza yardımcı olur." },
      { type: "p", text: "Özet: PMT formülü tek taksit için; detaylı plan için araç veya Excel tablosu." },
    ],
  },
  {
    slug: "excelde-yuzde-hesaplama",
    title: "Excel'de Yüzde Hesaplama: Artış, Düşüş, Oran—Anında Sonuç (Ücretsiz Araç)",
    description: "Yüzde artış, düşüş ve oran hesaplama: formül veya tek tıkla ücretsiz araç. En hızlı çözüm.",
    date: DATE,
    toolHref: "/excel-araclari/yuzde-hesaplama",
    toolName: "Yüzde Hesaplama",
    content: [
      { type: "p", text: "Yüzde artış, düşüş veya bir sayının diğerinin yüzde kaçı olduğunu hesaplamak Excel'de basit formüllerle yapılır." },
      { type: "h3", text: "Formüller" },
      { type: "ul", items: ["A'nın B'nin yüzde kaçı: =A/B veya =A/B%", "Yüzde artış: (yeni-eski)/eski.", "Yüzde düşüş: aynı formül; sonuç negatif olur.", "Belirli yüzde kadar artış: =eski*(1+oran)."] },
      { type: "h3", text: "Araç ile hesaplama" },
      { type: "p", text: "İki sayı girerek yüzde oranı, artış/düşüş veya hedeflenen yüzdeye ulaşmak için gerekli değeri hesaplayan araçlar sonucu anında verir." },
      { type: "p", text: "Özet: Günlük hesaplar için formül; hızlı tek hesaplar için araç." },
    ],
  },
  {
    slug: "excelde-tarih-farki-vade-gun-hesaplama",
    title: "Excel'de Tarih Farkı: Gün, Ay, Yaş Hesaplama—Tek Tıkla Sonuç (Ücretsiz Araç)",
    description: "İki tarih arası gün, ay, yaş: TARİHFARKI formülü veya toplu liste için ücretsiz araç. Hızlı çözüm.",
    date: DATE,
    toolHref: "/excel-araclari/tarih-farki",
    toolName: "Tarih Farkı (Vade / Gün / Yaş)",
    content: [
      { type: "p", text: "İki tarih arasındaki gün sayısı, vade veya yaş hesaplamak için Excel'de tarihleri çıkarmanız veya TARİHFARKI (DATEDIF) kullanmanız yeterli." },
      { type: "h3", text: "Formüller" },
      { type: "ul", items: ["Gün farkı: =Bitiş - Başlangıç (sayı olarak gün).", "Ay veya yıl: TARİHFARKI(başlangıç;bitiş;\"M\") veya \"Y\".", "Yaş: TARİHFARKI(doğum_tarihi;BUGÜN();\"Y\")."] },
      { type: "h3", text: "Araç ile toplu hesaplama" },
      { type: "p", text: "Başlangıç ve bitiş tarihlerini yapıştırıp gün, ay veya yıl farkını hesaplayan araçlar sonucu Excel'e yapıştırmaya uygun verir." },
      { type: "p", text: "Özet: Tek hesaplar için formül; uzun liste için araç." },
    ],
  },
  {
    slug: "excelde-tarih-format-donusturme",
    title: "Excel'de Tarih Formatı Değiştirme: Hızlı Çözüm + Ücretsiz Araç (GG.AA.YYYY, ISO)",
    description: "Tarihi GG.AA.YYYY, ISO veya uzun metne çevirme: METNEÇEVİR veya tek tıkla ücretsiz araç.",
    date: DATE,
    toolHref: "/excel-araclari/tarih-format-donusturucu",
    toolName: "Tarih Format Dönüştürücü",
    content: [
      { type: "p", text: "Tarihi GG.AA.YYYY, YYYY-MM-DD veya uzun metin (15 Mart 2025) formatında göstermek için Excel'de hücre formatı veya METNEÇEVİR kullanılır." },
      { type: "h3", text: "1. Yöntem: Hücre formatı" },
      { type: "p", text: "Hücreyi seçin → Sağ tık → Hücreleri Biçimlendir → Tarih veya Özel. GG.AA.YYYY, GGGG gibi kodlar kullanılır." },
      { type: "h3", text: "2. Yöntem: METNEÇEVİR" },
      { type: "p", text: "=METNEÇEVİR(tarih;\"GGGG AA YYYY\") gibi format kodlarıyla tarihi metne çevirebilirsiniz. Sonuç metin olur; sıralama için orijinal tarih sütununu kullanın." },
      { type: "h3", text: "Araç ile toplu dönüştürme" },
      { type: "p", text: "Tarih listesini yapıştırıp istediğiniz formata (ISO, Türkçe uzun, GG.AA.YYYY vb.) çeviren araçlar çıktıyı Excel'e yapıştırmaya uygun verir." },
      { type: "p", text: "Özet: Excel'de format veya METNEÇEVİR; toplu liste için araç." },
    ],
  },
  {
    slug: "excel-telefon-numarasi-formatlama",
    title: "Excel'de Telefon Numarası Formatlama: 0XXX XXX XX XX Tek Tıkla (Ücretsiz Araç)",
    description: "Telefon numarasını okunaklı formata çevirme: formül veya liste halinde ücretsiz araç. En hızlı çözüm.",
    date: DATE,
    toolHref: "/excel-araclari/telefon-formatlama",
    toolName: "Telefon Numarası Formatlama",
    content: [
      { type: "p", text: "Sadece rakam olarak duran telefon numaralarını okunaklı formata (0XXX XXX XX XX) çevirmek için Excel'de formül veya araç kullanılır." },
      { type: "h3", text: "1. Yöntem: Formül" },
      { type: "p", text: "11 haneli numara için SAĞ, SOL, PARÇAAL ile alan kodunu ve geri kalanı ayırıp araya boşluk koyarak birleştirebilirsiniz. 10 hane (başında 0 yok) ise önce 0 eklenir." },
      { type: "h3", text: "2. Yöntem: Araç" },
      { type: "p", text: "Numara listesini yapıştırıp yerel veya uluslararası formata çeviren araçlar sonucu Excel'e yapıştırmaya uygun verir." },
      { type: "p", text: "Özet: Az sayıda numara için formül; uzun liste için araç." },
    ],
  },
  {
    slug: "excel-email-liste-temizleme",
    title: "E-posta Listesi Temizleme: Geçersiz ve Tekrarları Tek Tıkla Ayıkla (Ücretsiz Araç)",
    description: "E-posta listesinde geçersiz adres ve tekrarları temizleme: Excel veya en hızlı çözüm—ücretsiz araç.",
    date: DATE,
    toolHref: "/excel-araclari/email-liste-temizleme",
    toolName: "E-posta Liste Temizleme",
    content: [
      { type: "p", text: "E-posta listesinde geçersiz formatlar, tekrarlar veya boş satırlar kampanya ve raporlarda sorun çıkarır. Temizlemek için basit kurallar veya araç kullanılır." },
      { type: "h3", text: "1. Yöntem: Excel'de" },
      { type: "ul", items: ["Yinelenenleri Kaldır ile tekrarları silin.", "Geçerli e-posta formatı için @ ve nokta kontrolü (formül veya filtre).", "Boş hücreleri silin veya filtreleyin."] },
      { type: "h3", text: "2. Yöntem: Araç" },
      { type: "p", text: "Listeyi yapıştırıp geçersiz ve tekrarları işaretleyen veya ayıklayan araçlar temiz listeyi Excel'e yapıştırmaya uygun verir." },
      { type: "p", text: "Özet: Temel temizlik Excel'de; toplu ve kurallı temizlik için araç." },
    ],
  },
  {
    slug: "excel-dosya-birlestirme",
    title: "Excel Dosyalarını Birleştirme: Çok Dosyayı Tek Tıkla Tek Dosyada Topla (Ücretsiz Araç)",
    description: "Aynı yapıdaki Excel dosyalarını tek dosyada birleştirme: Power Query veya tek tıkla ücretsiz araç.",
    date: DATE,
    toolHref: "/excel-araclari/excel-dosya-birlestirici",
    toolName: "Excel Dosya Birleştirici",
    content: [
      { type: "p", text: "Aynı kolon yapısına sahip birden fazla Excel dosyasını tek bir dosyada toplamak (her dosyanın satırlarını alt alta eklemek) raporlarda sık gerekiyor." },
      { type: "h3", text: "1. Yöntem: Manuel veya Power Query" },
      { type: "p", text: "Her dosyayı açıp veriyi kopyalayıp ana dosyaya yapıştırabilirsiniz. Power Query ile birden fazla dosyadan Veri Al → Birleştir ile otomatik birleştirme de yapılabilir." },
      { type: "h3", text: "2. Yöntem: Araç" },
      { type: "p", text: "Aynı yapıdaki dosyaları yükleyip tek Excel'de alt alta birleştiren araçlar tek tıkla sonuç dosyası üretir." },
      { type: "p", text: "Özet: Az dosya için kopyala-yapıştır; çok dosya için Power Query veya araç." },
    ],
  },
  {
    slug: "excel-sql-insert-donusturucu",
    title: "Excel'den SQL INSERT Oluşturma: Tabloyu Tek Tıkla Sorguya Çevir (Ücretsiz Araç)",
    description: "Excel tablosunu INSERT sorgularına dönüştürme: formül veya en hızlı çözüm—ücretsiz araç.",
    date: DATE,
    toolHref: "/excel-araclari/excel-sql-insert",
    toolName: "Excel → SQL INSERT Dönüştürücü",
    content: [
      { type: "p", text: "Excel'deki tabloyu veritabanına aktarmak için her satırı INSERT INTO ... VALUES (...) formatına çevirmek gerekir. Bunu formülle veya araçla yapabilirsiniz." },
      { type: "h3", text: "1. Yöntem: Formül" },
      { type: "p", text: "Her sütun için metin birleştirme ile 'INSERT INTO tablo (sütunlar) VALUES (' & A2 & ',' & B2 & ');' benzeri bir formül yazılabilir; tırnak ve virgül kaçışları dikkate alınmalı." },
      { type: "h3", text: "2. Yöntem: Araç" },
      { type: "p", text: "Tablo başlıkları ve veriyi yapıştırıp INSERT sorgularını üreten araçlar sonucu kopyalayıp SQL istemcisinde çalıştırmanızı sağlar." },
      { type: "p", text: "Özet: Az satır için formül; büyük tablo için araç daha güvenli ve hızlı." },
    ],
  },
  {
    slug: "excel-json-donusturucu",
    title: "Excel'i JSON'a Dönüştürme: Tabloyu Tek Tıkla JSON Yap (Ücretsiz Araç)",
    description: "Excel tablosunu JSON formatına çevirme: API ve entegrasyon için en hızlı çözüm—ücretsiz araç.",
    date: DATE,
    toolHref: "/excel-araclari/excel-json",
    toolName: "Excel → JSON Dönüştürücü",
    content: [
      { type: "p", text: "Excel'deki tabloyu JSON formatına (dizi veya nesneler) çevirmek API veya yazılım entegrasyonunda sık gerekiyor." },
      { type: "h3", text: "1. Yöntem: Formül / VBA" },
      { type: "p", text: "Excel'de satır satır okuyup sütun adlarıyla JSON nesnesi üreten formül karmaşık olur; genelde VBA veya dış araç kullanılır." },
      { type: "h3", text: "2. Yöntem: Araç" },
      { type: "p", text: "Tablo başlıkları ve veriyi yapıştırıp JSON çıktısı üreten araçlar sonucu kopyalayıp API veya koda yapıştırmanızı sağlar." },
      { type: "p", text: "Özet: Küçük tablo için manuel; büyük veya tekrarlayan iş için araç." },
    ],
  },
  {
    slug: "excel-ortalama-medyan-standart-sapma",
    title: "Excel'de Ortalama, Medyan, Standart Sapma: Tek Tıkla Tüm İstatistikler (Ücretsiz Araç)",
    description: "Excel'de ORTALAMA, ORTANCA, STDSAPMA veya liste yapıştır—anında betimsel istatistik. Ücretsiz araç.",
    date: DATE,
    toolHref: "/excel-araclari/betimsel-istatistik",
    toolName: "Ortalama, Medyan, Standart Sapma Hesaplama",
    content: [
      { type: "p", text: "Veri setinin merkezini ve yayılımını özetlemek için ortalama, medyan ve standart sapma sık kullanılır. Excel'de tek formüllerle veya toplu hesaplama aracıyla yapılabilir." },
      { type: "h3", text: "Formüller" },
      { type: "ul", items: ["ORTALAMA(aralık) — aritmetik ortalama.", "ORTANCA(aralık) — medyan (ortadaki değer).", "STDSAPMA.S(aralık) — örnek standart sapma.", "STDSAPMA.P(aralık) — popülasyon standart sapma."] },
      { type: "h3", text: "Araç ile toplu hesaplama" },
      { type: "p", text: "Sayı listesini yapıştırıp ortalama, medyan, standart sapma ve diğer betimsel istatistikleri üreten araçlar sonucu rapor veya Excel'e yapıştırmaya uygun verir." },
      { type: "p", text: "Özet: Tek aralık için formüller; birden fazla sütun veya dışarıdaki liste için araç." },
    ],
  },
  {
    slug: "excel-ceyrek-quartile-yuzdelik",
    title: "Excel'de Çeyrek ve Yüzdelik Hesaplama: Q1, Q3, %90 Tek Tıkla (Ücretsiz Araç)",
    description: "ÇEYREK.INC, YÜZDEBİRLİK.INC veya liste yapıştır—çeyrek ve yüzdelik anında. Ücretsiz araç.",
    date: DATE,
    toolHref: "/excel-araclari/ceyrek-yuzdelik",
    toolName: "Çeyrek ve Yüzdelik Hesaplama",
    content: [
      { type: "p", text: "Verinin çeyreklerini (Q1, Q2, Q3) veya belirli yüzdelik dilimlerini (örn. %90) hesaplamak kutu grafiği ve dağılım analizinde kullanılır." },
      { type: "h3", text: "Formüller" },
      { type: "ul", items: ["ÇEYREK.INC(aralık;1) — Q1, ÇEYREK.INC(aralık;2) — medyan, 3 — Q3.", "YÜZDEBİRLİK.INC(aralık;0,9) — %90 yüzdelik dilim."] },
      { type: "h3", text: "Araç ile hesaplama" },
      { type: "p", text: "Sayı listesini yapıştırıp çeyrek ve yüzdelik değerlerini hesaplayan araçlar sonucu Excel'e veya rapora aktarmanıza yardımcı olur." },
      { type: "p", text: "Özet: Excel'de ÇEYREK.INC ve YÜZDEBİRLİK.INC; toplu liste için araç." },
    ],
  },
  {
    slug: "excel-korelasyon-pearson-hesaplama",
    title: "Excel'de Korelasyon Hesaplama: İki Sütunu Anında Karşılaştır (Ücretsiz Araç)",
    description: "Excel'de KORELASYON (Pearson) veya iki sütun yapıştır—korelasyon anında. Ücretsiz araç.",
    date: DATE,
    toolHref: "/excel-araclari/korelasyon",
    toolName: "Korelasyon Hesaplama (Pearson)",
    content: [
      { type: "p", text: "İki sayısal değişken arasındaki doğrusal ilişkinin yönü ve gücü korelasyon katsayısıyla ölçülür. -1 ile +1 arasında değer alır." },
      { type: "h3", text: "Formül" },
      { type: "p", text: "=KORELASYON(A aralığı; B aralığı) ile Pearson korelasyon katsayısı hesaplanır. Pozitif değer birlikte artış, negatif birlikte ters yönü gösterir." },
      { type: "h3", text: "Araç ile hesaplama" },
      { type: "p", text: "İki sütun veriyi yapıştırıp korelasyonu hesaplayan araçlar sonucu yorumla birlikte verir; Excel'e uyumlu." },
      { type: "p", text: "Özet: İki sütun Excel'deyse KORELASYON; veri dışarıdaysa araç." },
    ],
  },
  {
    slug: "excel-z-score-z-skor-hesaplama",
    title: "Excel'de Z Skor Hesaplama: Aykırı Değerleri Tek Tıkla Bul (Ücretsiz Araç)",
    description: "Z skor ile aykırı değer tespiti: formül veya liste yapıştır—anında sonuç. Ücretsiz araç.",
    date: DATE,
    toolHref: "/excel-araclari/z-score",
    toolName: "Z Skor (Z-Score) Hesaplama",
    content: [
      { type: "p", text: "Z skor, bir değerin ortalamadan kaç standart sapma uzakta olduğunu gösterir. Aykırı değer tespiti ve karşılaştırma için kullanılır." },
      { type: "h3", text: "Formül" },
      { type: "p", text: "Z = (değer - ortalama) / standart_sapma. Excel'de: =(A1-ORTALAMA($A$1:$A$100))/STDSAPMA.S($A$1:$A$100). Mutlak değeri 2'den büyük olanlar genelde aykırı kabul edilir." },
      { type: "h3", text: "Araç ile toplu hesaplama" },
      { type: "p", text: "Sayı listesini yapıştırıp her değer için Z skor üreten araçlar sonucu Excel'e yapıştırmaya uygun verir." },
      { type: "p", text: "Özet: Tek sütun için formül; toplu liste için araç." },
    ],
  },
  {
    slug: "excel-frekans-dagilimi-hesaplama",
    title: "Excel'de Frekans Dağılımı: Histogram Verisini Tek Tıkla Çıkar (Ücretsiz Araç)",
    description: "FREKANS formülü veya veriyi yapıştır—sınıf aralıklarına göre sayım. Ücretsiz araç.",
    date: DATE,
    toolHref: "/excel-araclari/frekans-dagilimi",
    toolName: "Frekans Dağılımı Hesaplama",
    content: [
      { type: "p", text: "Veriyi belirli aralıklara (sınıflara) bölüp her aralıkta kaç gözlem olduğunu saymak histogram ve dağılım tablosu için gereklidir." },
      { type: "h3", text: "Formül" },
      { type: "p", text: "FREKANS(veri_aralığı; sınıf_üst_sınırları) dizi formülüdür; Ctrl+Shift+Enter ile girilir. Sınıf sınırlarını önceden (örn. 10, 20, 30) belirlemeniz gerekir." },
      { type: "h3", text: "Araç ile hesaplama" },
      { type: "p", text: "Veriyi ve sınıf genişliğini veya sınırları girerek frekans tablosu üreten araçlar sonucu Excel'e veya rapora aktarır." },
      { type: "p", text: "Özet: Dizi formülü kullanmak istemiyorsanız araç; otomatik sınıflama için araç daha pratik." },
    ],
  },
  {
    slug: "excel-basit-regresyon-dogrusal",
    title: "Excel'de Regresyon Hesaplama: Eğim, R² Tek Tıkla (Ücretsiz Araç)",
    description: "EĞİM, KESİŞİM, R kare: X-Y sütunlarını yapıştır—doğrusal regresyon anında. Ücretsiz araç.",
    date: DATE,
    toolHref: "/excel-araclari/basit-regresyon",
    toolName: "Regresyon Hesaplama (Doğrusal)",
    content: [
      { type: "p", text: "İki değişken arasında y = ax + b doğrusal ilişki kurmak için eğim (a) ve kesişim (b) hesaplanır. Tahmin ve trend analizinde kullanılır." },
      { type: "h3", text: "Formüller" },
      { type: "ul", items: ["EĞİM(Y; X) — eğim a.", "KESİŞİM(Y; X) — kesişim b.", "R kare: PEARSON(Y;X)^2 veya regresyon çıktısından."] },
      { type: "h3", text: "Araç ile hesaplama" },
      { type: "p", text: "X ve Y sütunlarını yapıştırıp eğim, kesişim ve R kare veren araçlar tahmin formülünü de üretir; Excel'e uyumlu." },
      { type: "p", text: "Özet: Excel'de EĞİM/KESİŞİM; toplu rapor için araç." },
    ],
  },
  {
    slug: "excel-formul-asistani",
    title: "Excel Formül Asistanı: İşe Göre Doğru Formülü Anında Bul (Ücretsiz)",
    description: "Ne yapmak istediğini yaz—uygun Excel formülü önerisi. En hızlı çözüm: ücretsiz asistan.",
    date: DATE,
    toolHref: "/excel-araclari/formul-asistani",
    toolName: "Excel Formül Asistanı",
    content: [
      { type: "p", text: "Ne yapmak istediğinizi tarif ederek uygun Excel formülünü bulmak için formül asistanı veya kısayol kartları kullanılabilir." },
      { type: "h3", text: "1. Yöntem: Excel Yardım ve öneriler" },
      { type: "p", text: "Hücreye = yazıp fonksiyon adının ilk harflerini yazınca Excel öneri listesi verir. Formül sekmesinde İşlev Ekle ile kategorilere göre arama yapabilirsiniz." },
      { type: "h3", text: "2. Yöntem: Formül asistanı aracı" },
      { type: "p", text: "İşlemi metinle tarif edip (örn. iki listede ortak olanları bul) uygun formül veya adımları öneren araçlar hızlı yol gösterir; sonucu kopyalayıp Excel'de kullanırsınız." },
      { type: "p", text: "Özet: Günlük kullanımda Excel önerisi; karmaşık senaryoda formül asistanı." },
    ],
  },
  {
    slug: "excel-duseyara-formul-olusturma",
    title: "Excel DÜŞEYARA Formülü: Adım Adım Oluşturucu (Ücretsiz Araç)",
    description: "DÜŞEYARA formülünü tablo ve sütun seçerek otomatik oluştur. En kolay yöntem—ücretsiz araç.",
    date: DATE,
    toolHref: "/excel-araclari/duseyara-olusturucu",
    toolName: "DÜŞEYARA Formül Oluşturucu",
    content: [
      { type: "p", text: "Bir tabloda arama değerine göre aynı satırdaki başka sütundaki değeri getirmek için DÜŞEYARA (VLOOKUP) kullanılır. Formül oluşturucu ile adım adım formül çıkarabilirsiniz." },
      { type: "h3", text: "Sözdizimi" },
      { type: "p", text: "=DÜŞEYARA(aranan;tablo_aralığı;sütun_sayısı;0). 0 tam eşleşme demektir. Aranan değer tablonun ilk sütununda aranır." },
      { type: "h3", text: "Araç ile formül oluşturma" },
      { type: "p", text: "Tablo aralığı, aranan hücre ve hangi sütunun getirileceğini seçerek hazır DÜŞEYARA formülünü üreten araçlar formülü kopyalayıp Excel'e yapıştırmanızı sağlar." },
      { type: "p", text: "Özet: Mantığı biliyorsanız doğrudan yazın; ilk kez kullanıyorsanız oluşturucu yardımcı." },
    ],
  },
  {
    slug: "excel-eger-formul-olusturma",
    title: "Excel EĞER Formülü: Koşula Göre Değer—En Kolay Oluşturucu (Ücretsiz Araç)",
    description: "EĞER formülü: koşul ve sonuçları seç, formül hazır. Tek tıkla çözüm—ücretsiz araç.",
    date: DATE,
    toolHref: "/excel-araclari/eger-olusturucu",
    toolName: "EĞER Formül Oluşturucu",
    content: [
      { type: "p", text: "Bir koşul doğruysa bir değer, yanlışsa başka değer göstermek için EĞER kullanılır. EĞER(koşul; doğruysa_değer; yanlışsa_değer)." },
      { type: "h3", text: "Örnek" },
      { type: "p", text: "=EĞER(A1>=50; \"Geçti\"; \"Kaldı\"). Koşul kısmında karşılaştırma operatörleri ve AND/OR (VE/VEYA) kullanılabilir." },
      { type: "h3", text: "Araç ile oluşturma" },
      { type: "p", text: "Koşulu ve doğru/yanlış değerlerini seçerek veya yazarak EĞER formülünü üreten araçlar formülü kopyalayıp Excel'de kullanmanızı sağlar." },
      { type: "p", text: "Özet: Basit EĞER için doğrudan yazın; karmaşık koşullarda oluşturucu hata azaltır." },
    ],
  },
  {
    slug: "excel-ic-ice-eger-coklu-kosul",
    title: "Excel İç İçe EĞER: Çoklu Koşul ve Puan Aralığı—Tek Tıkla Formül (Ücretsiz Araç)",
    description: "Puan aralığına göre harf notu: aralıkları gir, iç içe EĞER veya EĞERLER otomatik. Ücretsiz araç.",
    date: DATE,
    toolHref: "/excel-araclari/ic-ice-eger-olusturucu",
    toolName: "İç içe EĞER Oluşturucu",
    content: [
      { type: "p", text: "Birden fazla koşulda farklı sonuç vermek için EĞER içinde EĞER yazılır veya EĞERLER (IFS) kullanılır. Puan aralığına göre harf notu tipik örnektir." },
      { type: "h3", text: "İç içe EĞER örneği" },
      { type: "p", text: "=EĞER(A1>=90;\"A\";EĞER(A1>=80;\"B\";EĞER(A1>=70;\"C\";\"F\"))). EĞERLER ile: =EĞERLER(A1>=90;\"A\";A1>=80;\"B\";A1>=70;\"C\";DOĞRU;\"F\")." },
      { type: "h3", text: "Araç ile oluşturma" },
      { type: "p", text: "Aralıkları ve karşılık gelen değerleri girerek iç içe EĞER veya EĞERLER formülünü üreten araçlar uzun formülleri otomatik yazar." },
      { type: "p", text: "Özet: Çok koşulda EĞERLER daha okunabilir; araç her iki formülü de üretebilir." },
    ],
  },
  {
    slug: "excel-formul-aciklayici",
    title: "Excel Formül Açıklayıcı: Karmaşık Formülü Türkçe Anlat (Ücretsiz Araç)",
    description: "Formülü yapıştır—ne yaptığını adım adım Türkçe gör. Öğrenme ve hata ayıklama. Ücretsiz.",
    date: DATE,
    toolHref: "/excel-araclari/formul-aciklayici",
    toolName: "Excel Formül Açıklayıcı",
    content: [
      { type: "p", text: "Karmaşık bir formülün ne yaptığını anlamak veya başkasına anlatmak için formülü parçalara ayırıp açıklayan araçlar kullanılabilir." },
      { type: "h3", text: "Excel'de formül denetimi" },
      { type: "p", text: "Formüller → Formülü Değerlendir ile adım adım hesaplama izlenebilir. Hücre referansları renkle vurgulanır." },
      { type: "h3", text: "Araç ile açıklama" },
      { type: "p", text: "Formülü yapıştırıp Türkçe veya sade dilde ne yaptığını (hangi fonksiyon, hangi aralık) açıklayan araçlar öğrenme ve dokümantasyon için faydalıdır." },
      { type: "p", text: "Özet: Excel'de Değerlendir; metin açıklama için formül açıklayıcı araç." },
    ],
  },
  {
    slug: "excel-rapor-sablonlari",
    title: "Excel Rapor Şablonları: Hazır Özet Tablolar—Hızlı Başlangıç (Ücretsiz)",
    description: "Satış, stok, performans için hazır rapor şablonları. En hızlı çözüm—ücretsiz şablonlar.",
    date: DATE,
    toolHref: "/excel-araclari/rapor-sablonlari",
    toolName: "Otomatik Rapor Şablonları",
    content: [
      { type: "p", text: "Tekrarlayan raporları hızlandırmak için önceden yapılandırılmış şablonlar kullanılır: başlıklar, formüller ve özet alanları hazır olur." },
      { type: "h3", text: "1. Yöntem: Excel şablonları" },
      { type: "p", text: "Dosya → Yeni → Şablonlar veya kurumsal şablon kütüphanenizden rapor şablonu seçebilirsiniz. Pivot Tablo ve dilimleyicilerle etkileşimli raporlar da kurulabilir." },
      { type: "h3", text: "2. Yöntem: Hazır rapor şablonu seti" },
      { type: "p", text: "Satış, stok veya performans özeti için hazır yapıdaki şablonları indirip verinizi doldurarak kullanabilirsiniz; formüller ve grafikler otomatik güncellenir." },
      { type: "p", text: "Özet: Standart raporlar için şablon; özel ihtiyaç için kendi şablonunuzu kaydedin." },
    ],
  },
  {
    slug: "excel-hata-kontrol-checklist",
    title: "Excel Hata Kontrol Checklist'i: Veriyi Adım Adım Kontrol Et (Ücretsiz)",
    description: "Boş hücre, tekrar, format—veri kalitesi kontrol listesi. Rapor öncesi tek tıkla checklist.",
    date: DATE,
    toolHref: "/excel-araclari/hata-kontrol-checklist",
    toolName: "Hata Kontrol Checklist'i",
    content: [
      { type: "p", text: "Rapor veya analiz öncesi veride boşluk, tekrar, yanlış format veya tutarsızlık kontrolü yapmak hata oranını düşürür. Bir checklist ile adım adım kontrol edebilirsiniz." },
      { type: "h3", text: "Kontrol edilebilecekler" },
      { type: "ul", items: ["Boş hücreler (EBOŞSA, sayım).", "Yinelenen satırlar (Yinelenenleri Kaldır veya BENZERSİZ).", "Tarih/sayı metin karışımı (sayı olarak saklanan metin).", "Sütun tutarlılığı (beklenmeyen karakterler, uzunluk)."] },
      { type: "h3", text: "Checklist aracı" },
      { type: "p", text: "Hazır maddeleri işaretleyerek veri kalitesi kontrolünü tamamlayan checklist araçları eksik adım bırakmamanızı sağlar; rapor öncesi kullanılır." },
      { type: "p", text: "Özet: Küçük listelerde manuel; büyük veride checklist ile sistematik kontrol." },
    ],
  },
  /* ────────────────────────────────────────────────────
     SEO Blog Posts — Yüksek arama hacimli, araçsız rehberler
     ──────────────────────────────────────────────────── */
  {
    slug: "excel-pivot-tablo-nasil-yapilir",
    title: "Excel'de Pivot Tablo Nasıl Yapılır: Adım Adım Rehber (Başlangıçtan İleriye)",
    description: "Excel'de PivotTable oluşturma, veri özetleme, gruplama ve dilimleyici kullanımı. Sıfırdan adım adım anlatım.",
    date: "2026-03-24",
    guideHref: "/egitimler/ileri",
    guideName: "İleri Seviye Eğitim",
    content: [
      { type: "p", text: "Pivot tablo, Excel'deki en güçlü özetleme aracıdır. Binlerce satırlık veriyi birkaç tıkla kategoriye, aya veya bölgeye göre özetleyebilirsiniz — formül yazmadan." },
      { type: "h3", text: "Pivot tablo ne zaman kullanılır?" },
      { type: "ul", items: [
        "Satış verilerini aya veya ürüne göre toplamak istediğinizde.",
        "Büyük listede hangi kategorinin en yüksek olduğunu görmek istediğinizde.",
        "Aynı veriyi farklı açılardan (bölge, tarih, ürün) hızlıca analiz etmek istediğinizde.",
      ] },
      { type: "h3", text: "Adım 1: Veriyi hazırlayın" },
      { type: "p", text: "Her sütunun bir başlığı olmalı (Tarih, Ürün, Tutar gibi). Boş satır veya sütun olmamalı. Veriyi Ctrl+T ile tabloya çevirmek iyi bir pratiktir — yeni satır eklediğinizde pivot otomatik güncellenir." },
      { type: "h3", text: "Adım 2: Pivot tablo oluşturun" },
      { type: "ul", items: [
        "Tablonun herhangi bir hücresine tıklayın.",
        "Ekle sekmesi → PivotTable'a tıklayın.",
        "Yeni çalışma sayfası veya mevcut sayfada konum seçin.",
        "Tamam deyin.",
      ] },
      { type: "h3", text: "Adım 3: Alanları sürükleyin" },
      { type: "p", text: "Sağ tarafta PivotTable Alanları paneli açılır. Sütun başlıklarını Satırlar, Sütunlar, Değerler ve Filtreler kutularına sürükleyin. Örneğin: 'Ürün' → Satırlar, 'Tutar' → Değerler. Otomatik olarak ürün bazlı toplam görürsünüz." },
      { type: "h3", text: "Adım 4: Veriyi gruplayın" },
      { type: "p", text: "Tarih alanına sağ tıklayıp Grupla seçeneğiyle aylara veya yıllara göre gruplama yapabilirsiniz. Sayısal alanlarda belirli aralıklara göre gruplama da mümkün." },
      { type: "h3", text: "Adım 5: Dilimleyici (Slicer) ekleyin" },
      { type: "p", text: "Pivot tablo seçiliyken PivotTable Analiz → Dilimleyici Ekle ile görsel filtre butonları eklersiniz. Dilimleyiciye tıklayarak veriyi filtrelemek çok daha kolay ve görsel olur." },
      { type: "h3", text: "Sık yapılan hatalar" },
      { type: "ul", items: [
        "Başlıksız sütun bırakmak — pivot tablo hata verir.",
        "Boş satırlar — veri aralığının yanlış algılanmasına neden olur.",
        "Veri güncellendikten sonra pivotu yenilememek — sağ tık → Yenile veya Ctrl+Alt+F5.",
      ] },
      { type: "p", text: "Özet: Pivot tablo formül yazmadan veriyi özetlemenin en hızlı yoludur. Veriyi tabloya çevirin, Ekle → PivotTable deyin, alanları sürükleyin — bittiğinizde dilimleyiciyle etkileşimli bir rapor elde edersiniz." },
    ],
  },
  {
    slug: "excel-grafik-olusturma-rehberi",
    title: "Excel'de Grafik Oluşturma: Çubuk, Pasta, Çizgi — Adım Adım Rehber",
    description: "Excel'de grafik türleri, oluşturma adımları, biçimlendirme ve en iyi uygulamalar. Başlangıçtan ileriye rehber.",
    date: "2026-03-24",
    guideHref: "/egitimler/temel",
    guideName: "Temel Seviye Eğitim",
    content: [
      { type: "p", text: "Rakamları görsel hale getirmek, verideki trendleri ve karşılaştırmaları bir bakışta anlamak için grafikler kullanılır. Excel'de grafik oluşturmak birkaç tıklık iş; doğru grafik türünü seçmek önemli olan kısım." },
      { type: "h3", text: "Hangi grafik türü ne zaman?" },
      { type: "ul", items: [
        "Çubuk / Sütun grafik: Kategorileri karşılaştırmak (ör. ürün bazlı satışlar).",
        "Çizgi grafik: Zaman içindeki trendi göstermek (ör. aylık gelir).",
        "Pasta grafik: Parçaların bütüne oranını göstermek (ör. departman dağılımı). 5-6'dan fazla dilim varsa okunurluğu düşer.",
        "Karma grafik: Farklı ölçeklerdeki serileri aynı grafikte göstermek (ör. satış miktarı + kâr oranı).",
      ] },
      { type: "h3", text: "Grafik oluşturma adımları" },
      { type: "ul", items: [
        "Veri aralığını seçin (başlıklar dahil).",
        "Ekle sekmesi → Grafikler grubundan tür seçin.",
        "Alt tür seçin (yığılmış, kümelenmiş vb.).",
        "Grafik oluşturulur; sürükleyerek boyutunu ayarlayın.",
      ] },
      { type: "h3", text: "Grafik biçimlendirme" },
      { type: "p", text: "Grafiğe tıkladığınızda Grafik Tasarımı ve Biçim sekmeleri açılır. Başlık eklemek, eksen etiketlerini düzenlemek, renklerini değiştirmek ve veri etiketleri (sayıları çubukların üstüne yazmak) eklemek için bu sekmeleri kullanın." },
      { type: "h3", text: "Hızlı ipuçları" },
      { type: "ul", items: [
        "Alt+F1: Seçili veriyle anında varsayılan grafik oluşturur.",
        "F11: Yeni bir sayfa olarak grafik oluşturur.",
        "Grafikteki herhangi bir öğeye çift tıklayarak detaylı biçimlendirme panelini açabilirsiniz.",
        "Grafik stili değiştirmek için grafiğin sağ üstündeki fırça ikonunu kullanın.",
      ] },
      { type: "h3", text: "Dinamik grafik oluşturma" },
      { type: "p", text: "Verinizi Ctrl+T ile tabloya çevirirseniz tabloya yeni satır eklediğinizde grafik otomatik güncellenir. Bu sayede her ay grafiği yeniden oluşturmanız gerekmez." },
      { type: "p", text: "Özet: Veriyi seçin, Ekle → grafik türü seçin, biçimlendirin. Karşılaştırma için çubuk, trend için çizgi, oran için pasta kullanın. Veriyi tablo yaparsanız grafik otomatik büyür." },
    ],
  },
  {
    slug: "excel-acilir-liste-dropdown-yapma",
    title: "Excel'de Açılır Liste (Dropdown) Yapma: Adım Adım Rehber",
    description: "Excel'de veri doğrulama ile açılır liste oluşturma, dinamik liste ve bağımlı dropdown yapımı. Adım adım anlatım.",
    date: "2026-03-24",
    guideHref: "/egitimler/orta",
    guideName: "Orta Seviye Eğitim",
    content: [
      { type: "p", text: "Açılır liste (dropdown), hücreye yalnızca belirlediğiniz seçeneklerden birinin girilmesini sağlar. Veri girişi hatalarını azaltır, formları düzenli tutar ve rapor tutarlılığını artırır." },
      { type: "h3", text: "Yöntem 1: Sabit listeyle açılır liste" },
      { type: "ul", items: [
        "Açılır liste eklemek istediğiniz hücreleri seçin.",
        "Veri sekmesi → Veri Doğrulama'ya tıklayın.",
        "İzin Ver: Liste seçin.",
        "Kaynak kutusuna seçenekleri virgülle yazın: Evet,Hayır,Beklemede",
        "Tamam deyin. Hücrede aşağı ok butonu belirir.",
      ] },
      { type: "h3", text: "Yöntem 2: Hücre aralığından liste" },
      { type: "p", text: "Seçenekleri bir sütuna alt alta yazın (ör. E1:E5). Veri Doğrulama → Kaynak kutusunda bu aralığı seçin: =$E$1:$E$5. Avantajı: listeyi değiştirmek isterseniz sadece hücreleri güncelersiniz." },
      { type: "h3", text: "Yöntem 3: Dinamik liste (tablo ile)" },
      { type: "p", text: "Seçenekleri bir Excel tablosuna (Ctrl+T) çevirin. Kaynak kutusuna DOLAYLI(\"TabloAdı[SütunAdı]\") yazın. Tabloya yeni satır eklediğinizde açılır liste otomatik güncellenir." },
      { type: "h3", text: "Yöntem 4: Bağımlı açılır liste" },
      { type: "p", text: "İlk listede seçilen değere göre ikinci liste değişir. Örneğin: ilk listede 'Şehir' seçince ikinci listede o şehrin ilçeleri görünür. Bunun için her şehrin ilçelerini ayrı aralık adlarıyla tanımlayıp, ikinci listeye DOLAYLI(A1) formülü verilir." },
      { type: "h3", text: "İpuçları" },
      { type: "ul", items: [
        "Hata Uyarısı sekmesinden kullanıcıya özel mesaj gösterebilirsiniz.",
        "Giriş İletisi sekmesinden hücre seçildiğinde açıklama balonu çıkar.",
        "Birden fazla hücreye aynı anda Veri Doğrulama uygulamak için hücreleri önceden seçin.",
      ] },
      { type: "p", text: "Özet: Basit liste için virgüllü kaynak, güncellenebilir liste için hücre aralığı veya tablo, ikinci listenin birinciye bağlı olması için DOLAYLI formülü kullanın." },
    ],
  },
  {
    slug: "excel-kosullu-bicimlendirme-rehberi",
    title: "Excel'de Koşullu Biçimlendirme Nasıl Yapılır: Renk, İkon ve Formülle Vurgulama",
    description: "Excel'de koşullu biçimlendirme ile hücreleri renklendirme, veri çubukları, ikon setleri ve formül tabanlı kurallar.",
    date: "2026-03-24",
    guideHref: "/egitimler/orta",
    guideName: "Orta Seviye Eğitim",
    content: [
      { type: "p", text: "Koşullu biçimlendirme, belirlediğiniz kurala göre hücrelerin görünümünü otomatik değiştirir. Örneğin negatif sayıları kırmızı yapma, en yüksek 3 değeri vurgulama veya son teslim tarihi geçmiş satırları boyama gibi." },
      { type: "h3", text: "Hazır kurallar (en hızlı)" },
      { type: "ul", items: [
        "Hücre aralığını seçin.",
        "Giriş → Koşullu Biçimlendirme → Hücre Vurgulama Kuralları.",
        "Şundan Büyük, Şuna Eşit, Metin İçeren gibi seçeneklerden birini seçin.",
        "Değeri ve rengi belirleyin, Tamam deyin.",
      ] },
      { type: "h3", text: "Veri çubukları ve ikon setleri" },
      { type: "p", text: "Koşullu Biçimlendirme menüsünden Veri Çubukları seçerseniz hücrelerin içinde değerle orantılı bir çubuk çizilir. İkon Setleri ile yukarı/aşağı ok, trafik ışığı gibi görsel göstergeler ekleyebilirsiniz." },
      { type: "h3", text: "Formül tabanlı kural (en esnek)" },
      { type: "ul", items: [
        "Koşullu Biçimlendirme → Yeni Kural → Formül kullanarak biçimlendirilecek hücreleri belirle.",
        "Formül kutusuna bir mantıksal test yazın. Örn: =$C2<BUGÜN() (C sütunundaki tarih bugünden önceyse).",
        "Biçim butonuyla dolgu rengi, yazı rengi vb. seçin.",
        "Formül ilk satıra göre yazılır; Excel kuralı tüm seçili aralığa uygular.",
      ] },
      { type: "h3", text: "Formül örnekleri" },
      { type: "ul", items: [
        "Tüm satırı boyamak: =$D2=\"Tamamlandı\" — D sütunu 'Tamamlandı' olan satırlar yeşil.",
        "Yinelenen değerler: =EĞERSAY($A:$A;A2)>1 — tekrar eden hücreleri vurgular.",
        "Hafta sonu vurgulama: =HAFTANINGÜNÜ(A2;2)>5 — Cumartesi ve Pazar.",
      ] },
      { type: "h3", text: "Kuralları yönetme" },
      { type: "p", text: "Koşullu Biçimlendirme → Kuralları Yönet ile mevcut kuralları düzenleyebilir, sıralayabilir veya silebilirsiniz. Birden fazla kural varsa öncelik sırası önemlidir; yukarıdaki kural önce uygulanır." },
      { type: "p", text: "Özet: Basit vurgulama için hazır kurallar, görsel karşılaştırma için veri çubukları/ikonlar, tam kontrol için formül tabanlı kurallar kullanın." },
    ],
  },
  {
    slug: "excel-caprazara-xlookup-kullanimi",
    title: "Excel'de ÇAPRAZARA (XLOOKUP) Kullanımı: DÜŞEYARA'nın Modern Alternatifi",
    description: "XLOOKUP (ÇAPRAZARA) formülünün sözdizimi, DÜŞEYARA ile farkları, örnekler ve adım adım kullanım rehberi.",
    date: "2026-03-24",
    guideHref: "/egitimler/ileri",
    guideName: "İleri Seviye Eğitim",
    content: [
      { type: "p", text: "ÇAPRAZARA (XLOOKUP), Excel 365 ve Excel 2021 ile gelen modern bir arama fonksiyonudur. DÜŞEYARA ve YATAYARA'nın yerini alır; daha esnek, daha okunabilir ve daha az hataya açıktır." },
      { type: "h3", text: "Sözdizimi" },
      { type: "formula", label: "ÇAPRAZARA", formula: "=ÇAPRAZARA(arama_değeri; arama_aralığı; dönüş_aralığı; [bulunamadıysa]; [eşleşme_modu]; [arama_modu])" },
      { type: "ul", items: [
        "arama_değeri: Aradığınız değer (ör. A2).",
        "arama_aralığı: Değerin aranacağı sütun veya satır.",
        "dönüş_aralığı: Sonucun alınacağı sütun veya satır.",
        "[bulunamadıysa]: Değer bulunamazsa gösterilecek metin (ör. \"Bulunamadı\").",
        "[eşleşme_modu]: 0 = tam eşleşme (varsayılan), -1 = en yakın küçük, 1 = en yakın büyük.",
        "[arama_modu]: 1 = baştan sona (varsayılan), -1 = sondan başa.",
      ] },
      { type: "h3", text: "DÜŞEYARA ile farkları" },
      { type: "ul", items: [
        "DÜŞEYARA yalnızca sola bakamaz; ÇAPRAZARA herhangi bir yöne bakabilir.",
        "DÜŞEYARA sütun numarası ister (3. sütun gibi); ÇAPRAZARA doğrudan dönüş aralığını seçer — sütun eklendiğinde formül bozulmaz.",
        "ÇAPRAZARA'da bulunamadıysa parametresi var; DÜŞEYARA'da EĞERHATA ile sarmak gerekir.",
        "ÇAPRAZARA hem dikey hem yatay arama yapar; ayrı YATAYARA gerekmez.",
      ] },
      { type: "h3", text: "Örnek 1: Basit arama" },
      { type: "formula", label: "Ürün kodundan fiyat getirme", formula: "=ÇAPRAZARA(D2; $A$2:$A$100; $C$2:$C$100; \"Bulunamadı\")" },
      { type: "p", text: "D2'deki ürün kodunu A sütununda arar, aynı satırdaki C sütunundaki fiyatı getirir. Bulamazsa 'Bulunamadı' yazar." },
      { type: "h3", text: "Örnek 2: Sola arama (DÜŞEYARA yapamaz)" },
      { type: "formula", label: "Sağdaki sütundan soldaki sütuna arama", formula: "=ÇAPRAZARA(E2; $C$2:$C$100; $A$2:$A$100)" },
      { type: "p", text: "C sütununda arama yapıp A sütunundan sonuç alır. DÜŞEYARA ile bu mümkün değildir." },
      { type: "h3", text: "Örnek 3: Son eşleşmeyi bulma" },
      { type: "formula", label: "Arama modunu sondan başa ayarlama", formula: "=ÇAPRAZARA(\"Satış\"; $B$2:$B$100; $D$2:$D$100; ; 0; -1)" },
      { type: "p", text: "Arama modu -1 ile sondan başlayarak arar; bu listedeki son 'Satış' kaydını bulur." },
      { type: "h3", text: "Ne zaman ÇAPRAZARA kullanmalı?" },
      { type: "p", text: "Excel 365 veya 2021+ kullanıyorsanız yeni formüllerinizi ÇAPRAZARA ile yazmanız önerilir. Eski dosyalardaki DÜŞEYARA'ları değiştirmek zorunda değilsiniz ama yeni projelerde ÇAPRAZARA daha güvenli ve okunaklıdır." },
      { type: "p", text: "Özet: ÇAPRAZARA = daha esnek DÜŞEYARA. Her yöne bakabilir, sütun numarası gerektirmez, bulunamadıysa parametresi yerleşik. Excel 365/2021+ için standart arama fonksiyonu." },
    ],
  },
  {
    slug: "excel-nasil-kullanilir-baslangic-rehberi",
    title: "Excel Nasıl Kullanılır? Sıfırdan Başlayanlar İçin Adım Adım Rehber",
    description: "Excel nedir, nasıl açılır, veri girişi, temel formüller, biçimlendirme ve kaydetme. Yeni başlayanlar için eksiksiz rehber.",
    date: "2026-03-24",
    guideHref: "/egitimler/temel",
    guideName: "Temel Seviye Eğitim",
    content: [
      { type: "p", text: "Microsoft Excel, dünyada en çok kullanılan elektronik tablo programıdır. Veri girişi, hesaplama, grafik, analiz ve raporlama gibi birçok işi tek bir programda yapabilirsiniz. Bu rehberde sıfırdan başlayarak temel işlemleri adım adım öğreneceksiniz." },
      { type: "h3", text: "Excel arayüzünü tanıyın" },
      { type: "ul", items: [
        "Hücre: Satır ve sütunun kesiştiği kutu (ör. A1, B5).",
        "Çalışma sayfası: Alttaki sekmeler (Sayfa1, Sayfa2).",
        "Formül çubuğu: Hücredeki içeriği gösteren üst çubuk.",
        "Şerit (Ribbon): Giriş, Ekle, Veri gibi sekmelerin bulunduğu ana menü.",
      ] },
      { type: "h3", text: "Veri girişi" },
      { type: "p", text: "Bir hücreye tıklayıp yazmaya başlayın. Enter ile aşağıya, Tab ile sağa geçersiniz. Sayı, metin veya tarih girebilirsiniz. Tarihler GG.AA.YYYY formatında girilir." },
      { type: "h3", text: "Temel formüller" },
      { type: "ul", items: [
        "=A1+B1 — Toplama.",
        "=A1-B1 — Çıkarma.",
        "=A1*B1 — Çarpma.",
        "=A1/B1 — Bölme.",
        "=TOPLA(A1:A10) — A1'den A10'a kadar toplam.",
        "=ORTALAMA(A1:A10) — Ortalama.",
        "=MAK(A1:A10) — En büyük değer.",
        "=MİN(A1:A10) — En küçük değer.",
      ] },
      { type: "h3", text: "Hücre biçimlendirme" },
      { type: "ul", items: [
        "Kalın/italik/altı çizili: Giriş sekmesinden veya Ctrl+B, Ctrl+I, Ctrl+U.",
        "Sayı formatı: Hücreye sağ tık → Hücreleri Biçimlendir → Sayı/Para Birimi/Yüzde seçin.",
        "Hücre rengi: Giriş → Dolgu Rengi simgesi.",
        "Kenarlık: Giriş → Kenarlıklar simgesi.",
      ] },
      { type: "h3", text: "Sütun/satır ayarları" },
      { type: "p", text: "Sütun genişliğini ayarlamak için sütun başlığının kenarına çift tıklayın (otomatik sığdırma). Satır veya sütun eklemek için başlığa sağ tık → Ekle. Silmek için sağ tık → Sil." },
      { type: "h3", text: "Filtreleme ve sıralama" },
      { type: "p", text: "Veri → Filtre veya Ctrl+Shift+L ile başlıklara filtre butonları eklenir. Ok butonlarına tıklayarak belirli değerleri gösterip gizleyebilir veya A-Z / Z-A sıralayabilirsiniz." },
      { type: "h3", text: "Kaydetme" },
      { type: "ul", items: [
        "Ctrl+S: Mevcut dosyayı kaydet.",
        "F12 veya Dosya → Farklı Kaydet: Yeni isimle veya farklı formatta kaydet.",
        ".xlsx: Standart Excel formatı.",
        ".csv: Düz metin, diğer programlarla uyumlu.",
      ] },
      { type: "h3", text: "En önemli kısayollar" },
      { type: "ul", items: [
        "Ctrl+C / Ctrl+V: Kopyala / Yapıştır.",
        "Ctrl+Z: Geri al.",
        "Ctrl+Home: A1'e dön.",
        "Ctrl+End: Verinin son hücresine git.",
        "Ctrl+Shift+L: Filtre aç/kapat.",
        "Ctrl+;: Bugünün tarihini yaz.",
      ] },
      { type: "p", text: "Özet: Excel'de hücrelere veri girin, = ile formül yazın, biçimlendirin ve filtreleyin. Bu temel adımlarla günlük iş ihtiyaçlarınızın büyük çoğunluğunu karşılayabilirsiniz. Daha fazlası için eğitim sayfamıza göz atın." },
    ],
  },
  {
    slug: "excel-kisayol-formul-kartlari",
    title: "Excel Kısayol ve Formül Kartları: Tek Sayfada Hızlı Referans (Ücretsiz)",
    description: "Klavye kısayolları ve sık formüller tek sayfada. Yazdır, masada tut—ücretsiz kartlar.",
    date: DATE,
    toolHref: "/excel-araclari/ksayol-formul-kartlari",
    toolName: "Kısayol & Formül Kartları",
    content: [
      { type: "p", text: "Sık kullanılan Excel kısayolları ve formül özetlerini tek sayfada veya kart setinde bulmak hız kazandırır. Yazdırıp masada tutulabilir." },
      { type: "h3", text: "Kısayol örnekleri" },
      { type: "ul", items: ["Ctrl+C / Ctrl+V — kopyala yapıştır.", "Ctrl+; — bugünün tarihi.", "Ctrl+Shift+L — filtre.", "Alt+Enter — hücre içinde satır sonu."] },
      { type: "h3", text: "Formül kartları" },
      { type: "p", text: "ORTALAMA, DÜŞEYARA, EĞER, TOPLA.ÇARPIM gibi fonksiyonların sözdizimi ve kısa örneklerini içeren kartlar tek bakışta hatırlatma sağlar. Site üzerinden PDF veya sayfa olarak erişebilirsiniz." },
      { type: "p", text: "Özet: Günlük kullanımda kısayol ve formül kartları hızlı referans için idealdir." },
    ],
  },
];
