/**
 * Tüm Excel araçları — internal link (benzer araçlar) bileşeni ve SEO için tek kaynak.
 */

export type ExcelTool = { name: string; href: string };

export const EXCEL_TOOLS: ExcelTool[] = [
  { name: "Otomatik Rapor Şablonları", href: "/excel-araclari/rapor-sablonlari" },
  { name: "Hata Kontrol Checklist'i", href: "/excel-araclari/hata-kontrol-checklist" },
  { name: "Kısayol & Formül Kartları", href: "/excel-araclari/kisayol-formul-kartlari" },
  { name: "Ad Soyad Ayırıcı", href: "/excel-araclari/ad-soyad-ayir" },
  { name: "CSV Ayırıcı", href: "/excel-araclari/csv-ayir" },
  { name: "CSV Validator", href: "/excel-araclari/csv-dogrula" },
  { name: "Liste Birleştir / Ayır", href: "/excel-araclari/liste-birlestir" },
  { name: "Tekrarlananları Kaldır", href: "/excel-araclari/tekrarlananlari-kaldir" },
  { name: "Sayıyı Yazıya Çevir", href: "/excel-araclari/sayi-yaziya" },
  { name: "Satır / Sütun Döndür (Transpoz)", href: "/excel-araclari/transpoz" },
  { name: "Kelime & Karakter Sayacı", href: "/excel-araclari/kelime-karakter-sayaci" },
  { name: "Boşluk Temizle", href: "/excel-araclari/bosluk-temizle" },
  { name: "Sadece Sayı / Sadece Metin", href: "/excel-araclari/sayi-metin-ayikla" },
  { name: "Şirket Ünvanı Temizleyici", href: "/excel-araclari/sirket-unvan-temizle" },
  { name: "Türkçe → Slugify", href: "/excel-araclari/turkce-slugify" },
  { name: "Veri Ayıklayıcı", href: "/excel-araclari/veri-ayikla" },
  { name: "Metni Kolonlara Böl", href: "/excel-araclari/kolonlara-bol" },
  { name: "Büyük / Küçük Harf Dönüştür", href: "/excel-araclari/buyuk-kucuk-harf" },
  { name: "Hafta Numarası & Gün Adı", href: "/excel-araclari/hafta-gun" },
  { name: "IBAN Doğrulama", href: "/excel-araclari/iban-dogrulama" },
  { name: "Faiz Hesaplama", href: "/excel-araclari/faiz-hesaplama" },
  { name: "Kredi Taksit Hesaplama", href: "/excel-araclari/kredi-taksit" },
  { name: "Yüzde Hesaplama", href: "/excel-araclari/yuzde-hesaplama" },
  { name: "KDV Hesaplama", href: "/excel-araclari/kdv-hesapla" },
  { name: "Tarih Farkı (Vade / Gün / Yaş)", href: "/excel-araclari/tarih-farki" },
  { name: "Ortalama, Medyan, Standart Sapma Hesaplama", href: "/excel-araclari/betimsel-istatistik" },
  { name: "Çeyrek (Quartile) ve Yüzdelik Hesaplama", href: "/excel-araclari/ceyrek-yuzdelik" },
  { name: "Korelasyon Hesaplama (Pearson)", href: "/excel-araclari/korelasyon" },
  { name: "Z Skor (Z-Score) Hesaplama", href: "/excel-araclari/z-score" },
  { name: "Frekans Dağılımı Hesaplama", href: "/excel-araclari/frekans-dagilimi" },
  { name: "Excel Grafik Oluşturucu", href: "/excel-araclari/grafik-olusturucu" },
  { name: "Regresyon Hesaplama (Doğrusal)", href: "/excel-araclari/basit-regresyon" },
  { name: "Excel Formül Asistanı", href: "/excel-araclari/formul-asistani" },
  { name: "DÜŞEYARA Formül Oluşturucu", href: "/excel-araclari/duseyara-olusturucu" },
  { name: "EĞER Formül Oluşturucu", href: "/excel-araclari/eger-olusturucu" },
  { name: "İç içe EĞER Oluşturucu", href: "/excel-araclari/ic-ice-eger-olusturucu" },
  { name: "Excel Formül Açıklayıcı", href: "/excel-araclari/formul-aciklayici" },
  { name: "Excel → SQL INSERT Dönüştürücü", href: "/excel-araclari/excel-sql-insert" },
  { name: "SQL IN Formatter", href: "/excel-araclari/sql-in-formatter" },
  { name: "SQL UPDATE Formatter", href: "/excel-araclari/sql-update-formatter" },
  { name: "Excel ⇄ JSON", href: "/excel-araclari/excel-json" },
  { name: "Excel → Markdown Tablo", href: "/excel-araclari/excel-markdown" },
  { name: "İki Listeyi Karşılaştır", href: "/excel-araclari/iki-listeyi-karsilastir" },
  { name: "E-posta Liste Temizleme", href: "/excel-araclari/email-liste-temizleme" },
  { name: "Telefon Numarası Formatlama", href: "/excel-araclari/telefon-formatlama" },
  { name: "Tarih Format Dönüştürücü", href: "/excel-araclari/tarih-format-donusturucu" },
  { name: "Excel Dosya Birleştirici", href: "/excel-araclari/excel-dosya-birlestirici" },
];
